import React from 'react';

import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/Header';
import Masthead from '../components/Masthead';

const official = () => {
  return (
    <>
        <Head>
            <title>FakeMyFlight</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container lg grid grid-cols-1 gap-y-20 lg:grid-cols-5">
            <Header />
            <Masthead colSize={2}>Content here</Masthead>
            <Masthead colSize={3}>Form</Masthead>
        </main>
    </>
  )
}

export default official;