import React, { useState } from 'react';

import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/Header';
import MainForm from '../components/MainForm';
import Masthead from '../components/Masthead';

import Results from '../components/Results';

import OneWay from '../components/Oneway';
import RoundTrip from '../components/RoundTrip';

const official = () => {
  
  const [flights, setFlights] = useState(false);
  const [radio, setRadio] = useState(0);

  const oneWay = (radio === 0);
  const roundTrip = (radio === 1);

  return (
    <>
        <Head>
            <title>FakeMyFlight</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container lg p-5 grid grid-cols-1 gap-10 lg:gap-y-20 lg:grid-cols-5">
            <Header />
            <Masthead colSize={2}>Content</Masthead>
            <Masthead colSize={3}>
              <MainForm 
                radio={radio} 
                setRadio={setRadio} 
                setFlights={setFlights} />
              </Masthead>
        </main>
        {flights &&
          <Results>
            {(flights && oneWay) && <OneWay data={flights} />}
            {(flights && roundTrip) && <RoundTrip data={flights} />}
          </Results>
        }

    </>
  )
}

export default official;