import React from 'react';

import Head from 'next/head';
import Image from 'next/image';

const official = () => {
  return (
    <>
      <Head>
        <title>FakeMyFlight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default official;